# Generated by Django 2.2.28 on 2024-05-01 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20240501_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 5, 1, 14, 24, 33, 182037), verbose_name='Опубликована'),
        ),
    ]
