# Generated by Django 2.2.28 on 2024-05-03 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20240501_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 5, 3, 13, 56, 11, 851205), verbose_name='Опубликована'),
        ),
    ]
