# Generated by Django 2.2.28 on 2024-12-15 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20241215_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 15, 21, 49, 27, 61605), verbose_name='Опубликована'),
        ),
    ]
